INSERT INTO driver (ID,PREFIX,FIRST_NAME,LAST_NAME,TELEPHONE_NUMBER,
                    ADDRESS_LINE_ONE,ADDRESS_LINE_TWO,ADDRESS_CITY,
                    ADDRESS_POSTCODE,VEHICLE_TYPE,ENGINE_SIZE,
                    ADDITIONAL_DRIVERS,COMMERCIAL,
                    REGISTERED_OUTSIDE_STATE,VEHICLE_VALUE,DATE_REGISTERED,PREMIUM )
VALUES (1, 'Mrs','tom','blogs',012345,'12 SAMPLE STREET',
        '34 SAMPLE ROAD','SAMPLE CITY','123D4E','BUICK',
        500,1,'True','True',4000,'01/01/2021','150.22');